apiVersion: apps/v1
kind: Deployment
metadata:
  name: contconn-deployment-v02
  namespace: tauro-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contconn-label-v02
  template:
    metadata:
      labels:
        app: contconn-label-v02
    spec:
      containers:
        - name: contconn-container-v02
          image: lmldocker/contconn:1.0
          ports:
          - containerPort: 8321

# kubectl apply -f kube-deployment-v02.yaml
