apiVersion: v1
kind: Service
metadata:
  name: contconn-service-v02
  namespace: tauro-namespace
spec:
  type: NodePort
  selector:
    app: contconn-label-v02
  ports:
    - protocol: TCP
      port: 8321
      #targetPort: 8323
      #nodePort: 8666

# kubectl apply -f kube-service-v02.yaml
