apiVersion: apps/v1
kind: Deployment
metadata:
  name: contconn-deployment-v01
  namespace: tauro-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contconn-label-v01
  template:
    metadata:
      labels:
        app: contconn-label-v01
    spec:
      containers:
        - name: contconn-container-v01
          image: lmldocker/contconn:1.0
          ports:
          - containerPort: 8321

# kubectl apply -f kube-deployment-v01.yaml

#    kubectl expose deployment contconn-deployment-v01 --namespace=tauro-namespace --type NodePort --port 8321

#    minikube service service/contconn-deployment-v01 --namespace=tauro-namespace --url

